<?php

use function App\render_counter;

?>
<?= render_counter('cities') ?>
<div class="post">
    <div class="postheader"></div>
    <div class="postcontent">
        <h2>Список городов</h2>
        <!--вывод таблицы Города-->
        <form action="/cities/create.php" method="post" class="dopsity">
            <h3>Форма добовления города</h3>
            <input type="text" name="instextcity" required="" placeholder="Название города">
            <input type="text" name="instextrangir" required="" placeholder="Индекс Сортировки">
            <br>
            <input type="submit" value="Добавить" name="subminscity">
            <a href="/cities/index.php">Отмена</a>
        </form>
    </div>
    <div class="postbottom"></div>
</div>

